framework:
    messenger:
        default_bus: messenger.bus.default
        failure_transport: failed

        buses:
            messenger.bus.default: []

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                    delay: 1000
                    max_delay: 60000
            failed: 'doctrine://default?queue_name=failed'

        routing:
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
