security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider  # Utiliser le provider basé sur l'entité User
            custom_authenticator: App\Security\AuthAuthenticator
            logout:
                path: /logout       # Symfony écoutera les requêtes de déconnexion sur ce chemin
                target: /login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
       
        - { path: /user/, roles: ROLE_ADMIN } # Accès pour les enseignants
        - { path: /home2 , roles: ROLE_USER } # Accès pour les étudiants
        - { path: /home2, roles: ROLE_ARTIST }  # Accès pour les parents
