controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_user_pdf:
    path: /user/{id}/pdf
    controller: App\Controller\UserController::generateUserPdf
    methods: GET